'use scripts';

export const GET_ALL_CONTACTS = 'GET_ALL_CONTACTS';
export const CREATE_NEW_CONTACT = 'CREATE_NEW_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';

export const FAVORITES_CONTACT = 'FAVORITES_CONTACT';
export const ALL_FAVORITES_CONTACT = 'ALL_FAVORITES_CONTACT';


